### ISSUE TITLE
CoRL 2023 Paper

### ISSUE THREAD

**Issue by YanjieZe** [zubair-irshad/Awesome-Implicit-NeRF-Robotics#18]
GNFactor: Multi-Task Real Robot Learning with Generalizable Neural Feature Fields, [arXiv](https://arxiv.org/abs/2308.16891), [website](https://yanjieze.com/GNFactor/), and [code](https://github.com/YanjieZe/GNFactor)

**Comment by zubair-irshad** [comment]
Thanks for the mention. Can you please send a PR in this [format](https://github.com/zubair-irshad/Awesome-Implicit-NeRF-Robotics/blob/main/how-to-PR.md)?

**Comment by YanjieZe** [comment]
Yes, sure!
